dist: trusty
sudo: required
language: cpp

branches:
    except:
        - gh-pages

env:
    global:
        - GH_REPO_NAME: mania-pp
        - DOXYFILE: $TRAVIS_BUILD_DIR/doc/Doxyfile
        - GH_REPO_REF: github.com/TheMaximum/mania-pp.git

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.9
            - g++-4.9

            - doxygen
            - doxygen-doc
            - doxygen-latex
            - doxygen-gui
            - graphviz

script:
    - ./install.sh
    
    - cmake -DCMAKE_BUILD_TYPE=Debug -H. -Bbuild -DCMAKE_CXX_COMPILER=g++-4.9 -DCMAKE_C_COMPILER=gcc-4.9
    - cd ./build
    - make

after_success:
    - cd $TRAVIS_BUILD_DIR/doc
    - ./generate.sh
