config:
    server:
        address: '***'
        port: 5000
        authentication:
            username: 'SuperAdmin'
            password: '***'

    database:
        address: 'localhost'
        port: 3306
        authentication:
            username: '***'
            password: '***'
        database: 'maniapp'
