config:
    server:
        address: '***'
        port: 5000
        authentication:
            username: 'SuperAdmin'
            password: '***'

    database:
        address: 'localhost'
        port: 3306
        authentication:
            username: '***'
            password: '***'
        database: 'maniapp'

    program:
        checkVersion: false
        
plugins:
    - 'HelloGoodbye'
    - 'LocalRecords':
        limit: 100
        widgetEntries: 22
        widgetTopCount: 5
        widgetX: 49.2
        widgetY: 28.2
    - 'MapWidget'
